- hosts: localhost
  connection: local
    #vars_files:
    #- vars/{{ config_file }}.yml
  vars:
     user: "{{ lookup('env', 'USER') | default(lookup('env', 'LOGNAME')) }}"

  pre_tasks:
    - name: Create folder for repos needed
      file:
        path: "/home/{{ user }}/DalaDesktop/InstallRepos"
        state: directory
  
    #- name: Create folder for i3-glibc
    #  file:
    #    path: "/home/{{ user }}/DalaDesktop/InstallRepos/i3ipc-glibc"
    #    state: directory
        
    #- name: create folder for xfce4-i3-workspaces-plugin
    #  file:
    #    path: "/home/{{ user }}/DalaDesktop/InstallRepos/xfce4-i3-workspaces-plugin"
    #    state: directory

    - name: Backup original configs
      copy:
        src: "/home/{{ user }}/.config"
        dest: "/home/{{ user }}/configs-orig-backup"
    
    - name: Remove original directory
      file:
          path: "/home/{{ user }}/.config"
          state: absent

    - name: Create the .config directory
      file:
        src: "/home/{{ user }}/DalaDesktop/configs"
        dest: "/home/{{ user }}/.config"
        state: link

    - name: Ensure that bashrc is not already present
      file:
        path: "/home/{{ user }}/.bashrc"
        state: absent

    - name: Copy bashrc
      file:
        src: "/home/{{ user }}/DalaDesktop/CpToHome/.bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link

    - name: Copy dircolors
      file:
        src: "/home/{{ user }}/DalaDesktop/CpToHome/.dircolors"
        dest: "/home/{{ user }}/.dircolors"
        state: link

    #- name: create picture folder
    #  file:
    #    path: "/home/{{ user }}/Pictures/wallpapers"
    #    state: directory

    - name: copy backgrounds
      copy:
        src: "/home/{{ user }}/DalaDesktop/Backgrounds/"
        dest: "/home/{{ user }}/Pictures/wallpapers"
    
    - name: Get UID of target user
      command: id -u {{ user }}
      register: user_uid
      changed_when: false

    - name: Set UID fact
      set_fact:
        uid: "{{ user_uid.stdout }}"

  roles:
    - role: Hyprland
    - role: BasePrograms
    - role: BraveBrowser
    - role: InstallObsidian
