- hosts: localhost
  connection: local
    #vars_files:
    #- vars/{{ config_file }}.yml
  vars:
     user: "{{ lookup('env', 'USER') | default(lookup('env', 'LOGNAME')) }}"

  pre_tasks:
    - name: Create folder for repos needed
      file:
        path: "./InstallRepos"
        state: directory
  
    - name: Create folder for i3-glibc
      file:
        path: "./InstallRepos/i3ipc-glibc"
        state: directory
        
    - name: create folder for xfce4-i3-workspaces-plugin
      file:
        path: "./InstallRepos/xfce4-i3-workspaces-plugin"
        state: directory
    
    - name: Create the .config directory
      file:
        src: ".config"
        path: "/home/{{ user }}/.config"
        state: link

    - name: Copy bashrc
      file:
        src: "./CpToHome/.bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link

    - name: Copy dircolors
      file:
        src: "./CpToHome/.dircolors"
        dest: "/home/{{ user }}/.dircolors"
        state: link

    - name: create picture folder
      file:
        path: "/home/{{ user }}/Pictures"
        state: directory

    - name: copy backgrounds
      copy:
        src: "./Backgrounds/"
        dest: "/home/{{ user }}/Pictures"

  roles:
    - role: DEandWM
    - role: BasePrograms
    - role: BraveBrowser
    - role: InstallObsidian
