- hosts: localhost
  connection: local
  become: yes
    #vars_files:
    #- vars/{{ config_file }}.yml
  vars:
     user: "{{ lookup('env', 'USER') | default(lookup('env', 'LOGNAME')) }}"

  pre_tasks:
    - name: debug
      debug:
        var: user
    - name: Create folder for repos needed
      file:
        path: "/home/{{ user }}/InstallRepos"
        state: directory
      become: no
  
    - name: Create folder for i3-glibc
      file:
        path: "/home/{{ user }}/InstallRepos/i3ipc-glibc"
        state: directory
      become: no
        
    - name: create folder for xfce4-i3-workspaces-plugin
      file:
        path: "/home/{{ user }}/InstallRepos/xfce4-i3-workspaces-plugin"
        state: directory
      become: no
    
    - name: Create the .config directory
      file:
        path: "/home/{{ user }}/.config"
        state: directory
      become: no

    - name: Place the configs
      copy:
        src: "./configs/"
        dest: "/home/{{ user }}/.config/"
      become: no

        #- name: 

  roles:
    - role: DEandWM
      vars:
        user: "{{ user }}"
    - role: BasePrograms
      vars:
        user: "{{ user }}"


