- hosts: localhost
  connection: local
    #vars_files:
    #- vars/{{ config_file }}.yml
  vars:
     user: "{{ lookup('env', 'USER') | default(lookup('env', 'LOGNAME')) }}"

  pre_tasks:
    - name: Create folder for repos needed
      file:
        path: "/home/{{ user }}/InstallRepos"
        state: directory
  
    - name: Create folder for i3-glibc
      file:
        path: "/home/{{ user }}/InstallRepos/i3ipc-glibc"
        state: directory
        
    - name: create folder for xfce4-i3-workspaces-plugin
      file:
        path: "/home/{{ user }}/InstallRepos/xfce4-i3-workspaces-plugin"
        state: directory
    
    - name: Create the .config directory
      file:
        path: "/home/{{ user }}/.config"
        state: directory

    - name: Place the configs
      copy:
        src: "./configs/"
        dest: "/home/{{ user }}/.config/"

    - name: Copy bashrc
      copy:
        src: "./CpToHome/.bashrc"
        dest: "/home/{{ user }}/"

    - name: Copy dircolors
      copy:
        src: "./CpToHome/.dircolors"
        dest: "/home/{{ user }}/"

  roles:
    - role: DEandWM
    - role: BasePrograms
    - role: BraveBrowser
    - role: InstallObsidian
    - role: InstallCura
