---
- name: Add rpm fusion free repo
  command: dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  become: yes

- name: Add rpm fusion nonfree repo
  command: dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  become: yes

- name: install nvidia drivers
 dnf:
   name:
     - akmod-nvidia
     - xorg-x11-drv-nvidia

