---
- name: creare dir Downloads
  file:
    path: /home/{{ user }}/Downloads
    state: directory

- name: create dir Downloads/Cura_Extracted
  file:
    path: /home/{{ user }}/Downloads/Cura_Extracted
    state: directory

- name: Download Ultimaker Cura .AppImage
  get_url:
    url: "https://github.com/Ultimaker/Cura/releases/download/5.7.2-RC2/UltiMaker-Cura-5.7.2-linux-X64.AppImage"
    dest: /home/{{ user }}/Downloads/Ultimaker_Cura-5.4.0.AppImage
    mode: '0755'

- name: Make the .AppImage file executable
  file:
    path: /home/{{ user }}/Downloads/Ultimaker_Cura-5.4.0.AppImage
    mode: '0755'
    state: file

- name: Run the .AppImage file
  become: yes
  command: /home/{{ user }}/Downloads/Ultimaker_Cura-5.4.0.AppImage --appimage-extract
  args:
    chdir: /home/{{ user }}/Downloads/Cura_Extracted

