# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C4C7C7
background         #191919
cursor             #6E7070

active_tab_foreground     #191919
active_tab_background     #C4C7C7
inactive_tab_foreground   #C4C7C7
inactive_tab_background   #191919

active_border_color   #C4C7C7
inactive_border_color #191919
bell_border_color     #121313

color0      #3F4040
color1		#121313
color2		#121313
color3		#121313
color4		#151616
color5		#3D4445
color6		#404748
color7		#A2A7A7
color8		#717575
color9		#181919
color10		#181919
color11		#181919
color12		#1C1D1D
color13		#515B5C
color14		#555F60
color15		#A2A7A7
