- name: install the basic programs
  dnf:
    name:
      - alacritty
      - xfce4-whiskermenu-plugin
      - xfce4-systemload-plugin
      - picom
      - nitrogen
      - neovim
      - firefox
      - redshift-gtk
    state: present

- name: Create .vim folder
  file:
    path: "/home/{{ user }}/.vim"
    state: directory

- name: Copy nvimrc to the computer
  copy:
    src: "./nvimrc/"
    dest: "/home/{{ user }}/.vim"
