- name: Install the base programs
  become: yes
  dnf:
    name:
      - alacritty
      - xfce4-whiskermenu-plugin
      - xfce4-systemload-plugin
      - picom
      - nitrogen
      - neovim
      - firefox
      - redshift-gtk
      - gimp
        #- freecad
      - obs-studio
      - cheese
      - prusa-slicer
    state: present

- name: Create .vim folder
  file:
    path: "/home/{{ user }}/.vim"
    state: directory

- name: Copy nvimrc to the computer
  copy:
    src: "./nvimrc/.vim/"
    dest: "/home/{{ user }}/.vim"

- name: Download vimplug
  command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: install nvim plugins
  command: nvim +PlugInstall +qall
