- name: Install the base programs
  become: yes
  dnf:
    name:
      - neovim
      - firefox
      - gimp
        #- freecad
      - balena
      - obs-studio
      - cheese
      - prusa-slicer
      - gthumb
      - snapd
      - gnome-calculator
      - xprop
      - xdotool
      - pip
      - prusa-slicer
      - solaar
      - krita
      - go
      - virt-manager
    state: present

- name: Create .vim link
  file:
    src: "{{ ansible_env.PWD }}/nvimrc/.vim"
    dest: "/home/{{ user }}/.vim"
    state: link

- name: Download yarn
  command: npm install -g yarn
  become: yes

- name: Download vimplug
  command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: install nvim plugins
  command: nvim +PlugInstall +qall

  #- name: install markdown plugin
  #  command: nvim +call\ mkdp#util#install()


