---
- name: Ensure Flatpak is installed
  become: yes
  dnf:
    name: flatpak
    state: present

- name: Add the Flathub repository
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub.flatpakrepo

- name: Install Obsidian
  become: yes
  command: flatpak install -y flathub md.obsidian.Obsidian
  args:
    creates: /var/lib/flatpak/appstream/md.obsidian.Obsidian

