- name: Install xfce4 desktop environment
  become: yes
  dnf:
    name: 
      - '@xfce-desktop-environment'
      - xfce4-screensaver
    state: present

- name: Change default target to graphical.target
  become: yes
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Install i3 window manager and other dependencies around it
  become: yes
  dnf:
    name:
      - i3
      - xfce4-panel-devel
      - xfce4-dev-tools
      - 'libxfce4*'
      - libxcb
      - xcb-proto
      - glib
      - gobject-introspection
      - gobject-introspection-devel
      - json-glib
      - json-glib-devel
      - gtk-doc
      - autoconf
      - automake
      - libtool
    state: present

- name: Clone i3-glibc
  git:
    repo: "https://github.com/altdesktop/i3ipc-glib"
    dest: "./InstallRepos/i3ipc-glibc"
    version: "master"  # or any other branch/tag/commit
    update: yes

- name: reconfigure
  command: autoreconf -vfi
  args:
    chdir: "./InstallRepos/i3ipc-glibc"

- name: Run ./autogen for i3-glibc
  command: ./autogen.sh --prefix=/usr
  args:
    chdir: "./InstallRepos/i3ipc-glibc"

- name: Run make for i3-glibc
  command: make
  args:
    chdir: "./InstallRepos/i3ipc-glibc"

- name: Run sudo make install for i3ipc-glibc
  become: yes
  command: sudo make install
  args:
    chdir: "./InstallRepos/i3ipc-glibc"


- name: Clone xfce4-i3-workspaces-plugin
  git:
    repo: "https://github.com/denesb/xfce4-i3-workspaces-plugin.git"
    dest: "./InstallRepos/xfce4-i3-workspaces-plugin"
    version: "master"  # or any other branch/tag/commit
    update: yes

- name: Run ./autogen for workspaces plugin
  command: ./autogen.sh --prefix=/usr
  args:
    chdir: "./InstallRepos/xfce4-i3-workspaces-plugin"

- name: Run make for workspaces plugin
  command: make
  args:
    chdir: "./InstallRepos/xfce4-i3-workspaces-plugin"

- name: Run sudo make install for i3ipc-glibc
  command: sudo make install
  args:
    chdir: "./InstallRepos/xfce4-i3-workspaces-plugin"

- name: Uninstall i3status a i3lock
  become: yes
  dnf:
    name:
      - 'i3status*'
      - i3lock
    state: absent
