- name: Install xfce4 desktop environment
  dnf:
    name: 
      - '@xfce-desktop-environment'
    state: present

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Install i3 window manager and other dependencies around it
  dnf:
    name:
      - i3
      - xfce4-panel-devel
      - 'libxfce4*'
      - libxcb
      - xcb-proto
      - glib
      - gobject-introspection
      - json-glib
      - gtk-doc

- name: Create folder for repos needed
  file:
    path: "./InstallRepos"
    state: directory

- name: Create folder for i3-glibc
  file:
    path: "./InstallRepos/i3-glibc"
    state: directory

- name: Clone i3-glibc
  git:
    repo: "https://github.com/altdesktop/i3ipc-glib"
    dest: "./InstallRepos/i3-glibc"
    version: "main"  # or any other branch/tag/commit
    update: yes

- name: Run ./autogen for i3-glibc
  command: ./autogen.sh
  args:
    chdir: "./InstallRepos/i3-glibc"

- name: Run make for i3-glibc
  command: make
  args:
    chdir: "./InstallRepos/i3-glibc"

- name: Run sudo make install for i3-glibc
  command: sudo make install
  args:
    chdir: "./InstallRepos/i3-glibc"

#- name: Install xfce4-i3-workspace-plugin


#- name: Replace xfwm with i3




